In [2]:
import numpy as np

In [5]:
def neuron_output (x1, x2, w1, w2,b):
    """""
    A simple neuron :
    z = W1*X1 + W2*X2 + b
    Here we will NOT apply an activation yet, just return z
    """

    z = w1*x1 + w2*x2 + b
    return z

x1 = 5 
x2 = 2 

w1 = 0.8
w2 = 1.2
b = -1.0

z = neuron_output(x1, x2, w1, w2, b)
print("Linear combination (z) : ", z)

Linear combination (z) :  5.4


In [9]:
#5.1 Tiny 2 -layer neural network forward pass (no training)
np.random.seed(42)

#Input : 1 feature
x = np.array([[2.0],
              [1.0]]) #shape (2,1)

print(f'x : \n {x}')

x : 
 [[2.]
 [1.]]


In [ ]:
#Hidden layer : 3 neurons
#3 rows of weight for 3 neuron
# as many feature element as many column
W1 = np.random.randn(3,2) #weights for hidden layer (1x3)
b1 = np.random.randn(3,1) #bias for hidden layer (3x1)

print(f'W : \n {W1} \nB : \n {b1}')

W : 
 [[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]] 
B : 
 [[ 1.57921282]
 [ 0.76743473]
 [-0.46947439]]


In [ ]:
#Output layer : 1 neuron
W2 = np.random.randn(1,3) # weights for output layer (1x3)
b2 = np.random.randn(1,1) # bias for output ayer (1x1)

print(f'W2 : \n {W2}\n b2 : \n{b2}')

W2 : 
 [[ 0.49671415 -0.1382643   0.64768854]]
 b2 : 
[[1.52302986]]


In [14]:
def relu(z):
    return np.maximum(0,z)

def sigmoid(z):
    return 1/(1+np.exp(-z))

In [15]:
#Forward pass
#Hidden layer
z1 = np.dot(W1, x) +b #linear
a1 = relu(z1) #activation

print (f'z1 : \n {z1}\na1 : {a1}')

z1 : 
 [[-0.144836  ]
 [ 1.81840693]
 [-1.70244371]]
a1 : [[0.        ]
 [1.81840693]
 [0.        ]]


In [18]:
#Output layer

z2 = np.dot(W2, a1) + b2 # linear
a2 = sigmoid(z2)

print(f'z2 : \n {W2}\n a2 : \n {a2}')

z2 : 
 [[ 0.49671415 -0.1382643   0.64768854]]
 a2 : 
 [[0.78101807]]


In [17]:
print("Input x:\n", x)
print("\nHidden layer linear output (z1):\n", z1)
print("\nHidden layer activation (a1, after ReLU):\n", a1)
print("\nOutput layer linear output (z2):\n", z2)
print("\nFinal output (a2, after sigmoid – can be seen as probability):\n", a2)

Input x:
 [[2.]
 [1.]]

Hidden layer linear output (z1):
 [[-0.144836  ]
 [ 1.81840693]
 [-1.70244371]]

Hidden layer activation (a1, after ReLU):
 [[0.        ]
 [1.81840693]
 [0.        ]]

Output layer linear output (z2):
 [[1.27160909]]

Final output (a2, after sigmoid – can be seen as probability):
 [[0.78101807]]
