In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 2.0 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.9 MB 2.3 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.9 MB 2.3 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.9 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.9 MB 1.6 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.9 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.9 MB 1.8 MB/s eta 0:00:06
   ---------- ----------------------------- 3.4/12.9 MB 2.0 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.9 MB 2.1 MB/s eta 0:00:05
   ------------- -------------------------- 4.5/12.9 MB 2.2 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.9 MB 2.3 MB/s eta 0:00:04
   ------------------ --------------------- 6.0/12.9 MB 2.4 MB/s eta 0:00:03
   ---

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:

import numpy as np
print(np.__version__)

2.3.5


In [ ]:
#bring numpy library to the notebook/workbook.kernal
#numpy version attribute within the numpy class

In [6]:
python_list = [1,2,3,'string',6,7]

numlist = [x for x in range(10)]
print(numlist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
print(numlist*3)
print(type(numlist))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [13]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [15]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [ ]:
arr1D = np.array([1,2,3])
print(arr1D)



[1 2 3]


In [18]:
arr2D = np.array([[1,2,3],[1,2,3]])
print(arr2D)

[[1 2 3]
 [1 2 3]]


In [20]:
arr3D = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])
print(arr3D)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]


In [21]:
x = np.array([])
type(x)

numpy.ndarray

In [34]:
#ndim works on ojects and checks their dimension of an array!!
#ndim property

print(f'Dimension are : {arr1D.ndim}')
print(f'Dimension are : {arr2D.ndim}')
print(f'Dimension are : {arr3D.ndim}')

#using np.shape method for checking the 
#row, colum
print(f'Dimension are : {np.shape(arr1D)}')
print(f'Dimension are : {np.shape(arr2D)}')
print(f'Dimension are : {np.shape(arr3D)}')

np.ndim(arr1D)


arr1D.dtype

Dimension are : 1
Dimension are : 2
Dimension are : 3
Dimension are : (3,)
Dimension are : (2, 3)
Dimension are : (1, 4, 3)


dtype('int64')

In [33]:
shape1D = arr1D.size
shape1D

size1D=arr1D.size
size1D

size2D=arr2D.size
size2D

size3D=arr3D.size
size3D

12

In [39]:
#broadcasting

arr1D*30


array([30, 60, 90])

In [38]:
arr1D + arr1D

array([2, 4, 6])

In [ ]:
arr1=np.array([1,2,3,4,5,])
print(arr1)

arr2=np.array([10,20,30,40,50])
print(arr2)

print("Result : ", arr1+arr2)



[1 2 3 4 5]
[10 20 30 40 50]
Result :  [11 22 33 44 55]


In [42]:
prices = np.array([4000,3500,2500])
print(f'The price are : {prices/1000} million') #scale data

The price are : [4.  3.5 2.5] million


In [ ]:
#slicing
#reshaping

In [ ]:
#only list comprehension we have used
nums = [x for x in range(0,101,2)]
print (nums)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [ ]:
#range
#easisest way to create an array quickly

range_of_numbers = np.arrange(1,11)
range_of_numbers.reshape(5,2)
print(range_of_numbers)

#exactly same as this
range_example = np.arrange(1,11)



In [59]:
nums1 = nums[100:0:-1] #aaccssing element in list
nums1

[98,
 96,
 94,
 92,
 90,
 88,
 86,
 84,
 82,
 80,
 78,
 76,
 74,
 72,
 70,
 68,
 66,
 64,
 62,
 60,
 58,
 56,
 54,
 52,
 50,
 48,
 46,
 44,
 42,
 40,
 38,
 36,
 34,
 32,
 30,
 28,
 26,
 24,
 22,
 20,
 18,
 16,
 14,
 12,
 10,
 8,
 6,
 4,
 2]

In [55]:
nums2 = nums[0:50]
nums2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [56]:
nums3 = nums[0:50:-1]
nums3

[]

In [63]:
arraynums = np.array(nums)
print(arraynums)

print(arraynums[::2])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [ ]:
line = np.linspace(0,1,10) #value are evenly spaced and stored in array

line

#the result should be this :
#=[0.1,0.2,.04 ...]

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
array([1.,1.,1.]
      [1.,1.,1.]
      [1.,1.,1.]
      [1.,1.,1.])

In [ ]:
np.zeroes((3,3))
np.ones((3,3))

#take in tuples of shape, and return arrays

In [96]:
#random class in numpy

np.random.seed(40)

#randomArray = np.random.rand(3,4)
#randomArray

randomArray = np.random.randint(0,100,(3,4)) #start, stop, shape
randomArray


array([[70, 91,  7, 37],
       [56, 50, 65, 12],
       [71, 19, 31, 74]], dtype=int32)

In [ ]:
#change and reshape

#transform, linear algebra

In [97]:
randomArray

array([[70, 91,  7, 37],
       [56, 50, 65, 12],
       [71, 19, 31, 74]], dtype=int32)

In [98]:
flatArray =randomArray.flatten()
flatArray

array([70, 91,  7, 37, 56, 50, 65, 12, 71, 19, 31, 74], dtype=int32)

In [100]:
reshapeArray = flatArray.reshape(2,6)
reshapeArray

array([[70, 91,  7, 37, 56, 50],
       [65, 12, 71, 19, 31, 74]], dtype=int32)

In [101]:
#transform
reshapeArray.T

array([[70, 65],
       [91, 12],
       [ 7, 71],
       [37, 19],
       [56, 31],
       [50, 74]], dtype=int32)

In [103]:
#aggregations

data = np.array((85,94,22,68,94,54,98)) #marks

#sum
#mean
#minimum
#max

print(data.sum())

515


In [107]:
#Create a lsit of 1 to 10
#use list compreshension
#give me the addtion of numbers from 1 to 10

numbs= np.array((1,2,3,4,5,6,7,8,9,10))
print ('The total number 1 to 10 is ',numbs.sum())


The total number 1 to 10 is  55


In [115]:

numbers= [a for a in range(1,11)]
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [116]:
total = sum(numbers)
total

55

In [ ]:
#list comprehension (number : expression)

array_athirah = np.array((num for num in range(1,11)))
sum_of_array_athirah = array_athirah.sum()
print(sum_of_array_athirah)
array_athirah.mean()

Whle thing!!!
but we can also go,column wise
or
row wise


In [130]:
a_2d_matrix = np.ones((3,5))
print(a_2d_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [132]:
#column wise sum
a_2d_matrix.sum(axis=0)

a_2d_matrix.sum(axis=1) #row wise

array([5., 5., 5.])

In [ ]:
#range
#easisest way to create an array quickly

range_example = np.arrange(1,101).reshape(50,2)
print(range_example)

train_datset = dataset_array[1:10]
train_datset

In [ ]:
train_dataset = dataset_array[:25]

test_dataset = dataset_array[:25]
