In [2]:
list2 =[3,4,5,'athirah',4.5,[3,['a','b'],5]]
list2[5][1][0]

'a'

In [6]:
vector1 = [3,4,20]

vector2 = [2,4,10]

vector3 = [30,4,10]

In [7]:
matrix= [vector1,vector2,vector3]

matrix

[[3, 4, 20], [2, 4, 10], [30, 4, 10]]

In [8]:
type(vector1)

list

In [9]:
type(matrix)

list

In [3]:
matrix2 = [vector1,vector2]
matrix2

[[3, 4, 20], [2, 4, 10]]

In [5]:
matrix2[1]

[2, 4, 10]

In [4]:
matrix2[1][0]

2

In [13]:
import numpy as np

In [15]:
arr = np.array(vector1)
arr

array([ 3,  4, 20])

In [18]:
matrix[0:2]

[[3, 4, 20], [2, 4, 10]]

In [ ]:
arr.max()
arr.min()
arr.mean()
arr.var() # 8.0
arr.std()

In [ ]:
#how to check dimension in the list

In [16]:
matrix= [
    [3,4,20],
    [2,4,10],
    [30,4,10]]

matrixarr=np.array(matrix)

In [17]:
type(matrixarr)

matrixarr.ndim

2

In [23]:
matrixarr[1:2][0]

array([ 2,  4, 10])

In [25]:
matrix *2 #scalar multiplication

#scaler operation with array

#matrix * 10

[[3, 4, 20], [2, 4, 10], [30, 4, 10], [3, 4, 20], [2, 4, 10], [30, 4, 10]]

In [ ]:
matrixarr.ndim
matrixarr.shape;.

In [ ]:
a = np.array(
    [[1,3,5,6],
     2,8,7,9]
)

b = np.array([10,10,10,10])

print(a-b)
print(a*b)
print(a/b)
print(a+b)

In [ ]:
aa = np.array(
    [[1,3,5,6],
     2,8,7,9]
)

bb = np.array(
    [[10],
    [10]])


a*b


In [39]:
covariance = np.array([145325,24355])

n = np.array([145, 542,355,3456])

In [34]:
((variance)**0.5).round(2)

array([ 381.22,  156.06,  650.8 , 1877.09])

In [35]:
stdx,stdy = np.array([ 381.22,  156.06])

In [38]:
r = covariance/(stdx*stdy)
r

array([ 2.44271642,  0.40937456,  7.11918418, 59.22452318])